### ISSUE TITLE
the tables is not variables

### ISSUE THREAD

**Issue by youssriaboelseod** [Hubertchenxdd/python_app_sqlite#1]
hi Hubertchenxdd
thanks for your best App

but you named your table to select it , 

i search about how can it get as varibles 

for example 
if you rename you table you will get error in your app

**Comment by Hubertchenxdd** [comment]
Hi @youssriaboelseod,

Thanks for your kind response. You are correct. This app UI is designed for such data schema and it doesn't have the capability to import databases with different schemas. If you would like to make the table names variables, I believe that sqlite3 has commands such as .table to return the list of table names.
